SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE `sik`.`penilaian_lanjutan_resiko_jatuh_psikiatri`  (
  `no_rawat` varchar(17) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `tanggal` datetime NOT NULL,
  `penilaian_jatuhedmonson_skala1` enum('-','Kurang Dari 50 Th','50 - 70 Th','Lebih Dari 70 Th') CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `penilaian_jatuhedmonson_nilai1` tinyint(4) NULL DEFAULT NULL,
  `penilaian_jatuhedmonson_skala2` enum('-','Kesadaran/Orientasi Baik Setiap Saat','Agitasi/Ansietas','Kadang-kadang Bingung','Bingung/Disorientasi') CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `penilaian_jatuhedmonson_nilai2` tinyint(4) NULL DEFAULT NULL,
  `penilaian_jatuhedmonson_skala3` enum('-','Mandiri & Mampu Mengontrol BAB/BAK','Dower Catheter/Colostomy','Eliminasi Dengan Bantuan','Gangguan Eliminasi (Inkontinensia/Nokturia/Frekuensi)','Inkontinensia Tetapi Mampu Untuk Mobilisasi') CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `penilaian_jatuhedmonson_nilai3` tinyint(4) NULL DEFAULT NULL,
  `penilaian_jatuhedmonson_skala4` enum('-','Tanpa Obat-obatan','Obat-obatan Jantung','Obat-obatan Psikotropika (Termasuk Benzodiazepine & Antidepresan)','Mendapat Tambahan Obat-obatan & Atau Obat PRN Selama 24 Jam Terakhir') CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `penilaian_jatuhedmonson_nilai4` tinyint(4) NULL DEFAULT NULL,
  `penilaian_jatuhedmonson_skala5` enum('-','Bipolar/Gangguan Schizoaffective','Penggunaan Obat-obatan Terlarang, Ketergantungan Alkohol','Gangguan Depresi Mayor','Demensia/Delirium') CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `penilaian_jatuhedmonson_nilai5` tinyint(4) NULL DEFAULT NULL,
  `penilaian_jatuhedmonson_skala6` enum('-','Mandiri/Keseimbangan Baik/Imobilisasi','Dengan Alat Bantu (Kursi Roda, Walker, Dll)','Vertigo/Kelemahan','Goyah/Membutuhkan Bantuan & Menyadari Kemampuan','Goyah Tapi Lupa Keterbatasan') CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `penilaian_jatuhedmonson_nilai6` tinyint(4) NULL DEFAULT NULL,
  `penilaian_jatuhedmonson_totalnilai` tinyint(4) NULL DEFAULT NULL,
  `hasil_skrining` varchar(200) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `saran` varchar(200) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `nip` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  PRIMARY KEY (`no_rawat`, `tanggal`) USING BTREE,
  INDEX `nip`(`nip`) USING BTREE,
  CONSTRAINT `penilaian_lanjutan_resiko_jatuh_psikiatri_ibfk_1` FOREIGN KEY (`no_rawat`) REFERENCES `sik`.`reg_periksa` (`no_rawat`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `penilaian_lanjutan_resiko_jatuh_psikiatri_ibfk_2` FOREIGN KEY (`nip`) REFERENCES `sik`.`petugas` (`nip`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

CREATE TABLE `sik`.`penilaian_level_kecemasan_ranap_anak`  (
  `no_rawat` varchar(17) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `tanggal` datetime NOT NULL,
  `cemas` tinyint(4) NULL DEFAULT NULL,
  `firasat_buruk` tinyint(4) NULL DEFAULT NULL,
  `takut_pikiran_sendiri` tinyint(4) NULL DEFAULT NULL,
  `mudah_tersinggung` tinyint(4) NULL DEFAULT NULL,
  `merasa_tegang` tinyint(4) NULL DEFAULT NULL,
  `lesu` tinyint(4) NULL DEFAULT NULL,
  `tak_bisa_istirahat_tenang` tinyint(4) NULL DEFAULT NULL,
  `mudah_terkejut` tinyint(4) NULL DEFAULT NULL,
  `mudah_menangis` tinyint(4) NULL DEFAULT NULL,
  `gemetar` tinyint(4) NULL DEFAULT NULL,
  `gelisah` tinyint(4) NULL DEFAULT NULL,
  `takut_pada_gelap` tinyint(4) NULL DEFAULT NULL,
  `takut_pada_orangasing` tinyint(4) NULL DEFAULT NULL,
  `takut_pada_kerumunan_banyak_orang` tinyint(4) NULL DEFAULT NULL,
  `takut_pada_binatang_besar` tinyint(4) NULL DEFAULT NULL,
  `takut_pada_keramaian_lalu_lintas` tinyint(4) NULL DEFAULT NULL,
  `takut_ditinggal_sendiri` tinyint(4) NULL DEFAULT NULL,
  `sulit_tidur` tinyint(4) NULL DEFAULT NULL,
  `terbangun_malam_hari` tinyint(4) NULL DEFAULT NULL,
  `tidur_tidak_nyeyak` tinyint(4) NULL DEFAULT NULL,
  `mimpi_buruk` tinyint(4) NULL DEFAULT NULL,
  `bangun_dengan_lesu` tinyint(4) NULL DEFAULT NULL,
  `banyak_mengalami_mimpi` tinyint(4) NULL DEFAULT NULL,
  `mimpi_menakutkan` tinyint(4) NULL DEFAULT NULL,
  `sulit_konsentrasi` tinyint(4) NULL DEFAULT NULL,
  `daya_ingat_buruk` tinyint(4) NULL DEFAULT NULL,
  `hilangnya_minat` tinyint(4) NULL DEFAULT NULL,
  `berkurangnya_kesenangan_pada_hobi` tinyint(4) NULL DEFAULT NULL,
  `sedih` tinyint(4) NULL DEFAULT NULL,
  `bangun_dini_hari` tinyint(4) NULL DEFAULT NULL,
  `perasaan_berubah` tinyint(4) NULL DEFAULT NULL,
  `sakit_nyeri_di_otot` tinyint(4) NULL DEFAULT NULL,
  `kaku` tinyint(4) NULL DEFAULT NULL,
  `kedutan_otot` tinyint(4) NULL DEFAULT NULL,
  `gigi_gemerutuk` tinyint(4) NULL DEFAULT NULL,
  `suara_tidak_stabil` tinyint(4) NULL DEFAULT NULL,
  `tinnitus` tinyint(4) NULL DEFAULT NULL,
  `penglihatan_kabur` tinyint(4) NULL DEFAULT NULL,
  `muka_merah_gejala_somatic` tinyint(4) NULL DEFAULT NULL,
  `merasa_lemah` tinyint(4) NULL DEFAULT NULL,
  `perasaan_ditusuk` tinyint(4) NULL DEFAULT NULL,
  `takhikardia` tinyint(4) NULL DEFAULT NULL,
  `berdebar` tinyint(4) NULL DEFAULT NULL,
  `nyeri_di_dada` tinyint(4) NULL DEFAULT NULL,
  `denyut_nadi_mengeras` tinyint(4) NULL DEFAULT NULL,
  `perasaan_lesu` tinyint(4) NULL DEFAULT NULL,
  `detak_jantung_menghilang` tinyint(4) NULL DEFAULT NULL,
  `merasa_tertekan` tinyint(4) NULL DEFAULT NULL,
  `perasaan_tercekik` tinyint(4) NULL DEFAULT NULL,
  `sering_menarik_napas` tinyint(4) NULL DEFAULT NULL,
  `napas_pendek` tinyint(4) NULL DEFAULT NULL,
  `bulu_berdiri` tinyint(4) NULL DEFAULT NULL,
  `sulit_menelan` tinyint(4) NULL DEFAULT NULL,
  `perut_melilit` tinyint(4) NULL DEFAULT NULL,
  `ganguan_pencernaan` tinyint(4) NULL DEFAULT NULL,
  `rasa_kembung` tinyint(4) NULL DEFAULT NULL,
  `nyeri_makan` tinyint(4) NULL DEFAULT NULL,
  `terbakar_perut` tinyint(4) NULL DEFAULT NULL,
  `sukar_bab` tinyint(4) NULL DEFAULT NULL,
  `muntah` tinyint(4) NULL DEFAULT NULL,
  `bab_lembek` tinyint(4) NULL DEFAULT NULL,
  `kehilangan_bb` tinyint(4) NULL DEFAULT NULL,
  `mual` tinyint(4) NULL DEFAULT NULL,
  `sering_bak` tinyint(4) NULL DEFAULT NULL,
  `tidak_bisa_menahan_kencing` tinyint(4) NULL DEFAULT NULL,
  `menjadi_dingin` tinyint(4) NULL DEFAULT NULL,
  `manorrhagia` tinyint(4) NULL DEFAULT NULL,
  `amenorrhoea` tinyint(4) NULL DEFAULT NULL,
  `ejakulasi_praecocks` tinyint(4) NULL DEFAULT NULL,
  `ereksi_hilang` tinyint(4) NULL DEFAULT NULL,
  `impotensi` tinyint(4) NULL DEFAULT NULL,
  `mulut_kering` tinyint(4) NULL DEFAULT NULL,
  `muka_merah_gejala_otonom` tinyint(4) NULL DEFAULT NULL,
  `mudah_berkeringat` tinyint(4) NULL DEFAULT NULL,
  `bulu_berdiri_gejala_otonom` tinyint(4) NULL DEFAULT NULL,
  `sakit_kepala` tinyint(4) NULL DEFAULT NULL,
  `gelisah_wawancara` tinyint(4) NULL DEFAULT NULL,
  `napas_pendek_wawancara` tinyint(4) NULL DEFAULT NULL,
  `jari_gemetar` tinyint(4) NULL DEFAULT NULL,
  `kerut_kening` tinyint(4) NULL DEFAULT NULL,
  `muka_tegang` tinyint(4) NULL DEFAULT NULL,
  `tonus_meningkat` tinyint(4) NULL DEFAULT NULL,
  `tidak_tenang` tinyint(4) NULL DEFAULT NULL,
  `muka_merah_wawancara` tinyint(4) NULL DEFAULT NULL,
  `total_skor` int(4) NULL DEFAULT NULL,
  `keterangan_skor` enum('Tidak Mengalami Kecemasan','Kecemasan Ringan','Kecemasan Sedang','Kecemasan Berat','Kecemasan Sangat Berat') CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `nip` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  PRIMARY KEY (`no_rawat`, `tanggal`) USING BTREE,
  INDEX `nip`(`nip`) USING BTREE,
  CONSTRAINT `penilaian_level_kecemasan_ranap_anak_ibfk_1` FOREIGN KEY (`no_rawat`) REFERENCES `sik`.`reg_periksa` (`no_rawat`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `penilaian_level_kecemasan_ranap_anak_ibfk_2` FOREIGN KEY (`nip`) REFERENCES `sik`.`petugas` (`nip`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

CREATE TABLE `sik`.`penilaian_medis_hemodialisa`  (
  `no_rawat` varchar(17) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `tanggal` datetime NULL DEFAULT NULL,
  `kd_dokter` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `anamnesis` enum('Autoanamnesis','Alloanamnesis') CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `hubungan` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `ruangan` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `alergi` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `nyeri` enum('Tidak Nyeri','Nyeri Ringan','Nyeri Sedang','Nyeri Berat','Nyeri Sangat Berat','Nyeri Tak Tertahankan') CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `status_nutrisi` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `hipertensi` enum('Tidak','Ya') CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `keterangan_hipertensi` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `diabetes` enum('Tidak','Ya') CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `keterangan_diabetes` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `batu_saluran_kemih` enum('Tidak','Ya') CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `keterangan_batu_saluran_kemih` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `operasi_saluran_kemih` enum('Tidak','Ya') CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `keterangan_operasi_saluran_kemih` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `infeksi_saluran_kemih` enum('Tidak','Ya') CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `keterangan_infeksi_saluran_kemih` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `bengkak_seluruh_tubuh` enum('Tidak','Ya') CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `keterangan_bengkak_seluruh_tubuh` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `urin_berdarah` enum('Tidak','Ya') CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `keterangan_urin_berdarah` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `penyakit_ginjal_laom` enum('Tidak','Ya') CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `keterangan_penyakit_ginjal_laom` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `penyakit_lain` enum('Tidak','Ya') CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `keterangan_penyakit_lain` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `konsumsi_obat_nefro` enum('Tidak','Ya') CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `keterangan_konsumsi_obat_nefro` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `dialisis_pertama` date NOT NULL,
  `pernah_cpad` enum('Tidak','Ya') CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `tanggal_cpad` date NOT NULL,
  `pernah_transplantasi` enum('Tidak','Ya') CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `tanggal_transplantasi` date NOT NULL,
  `keadaan_umum` enum('Sehat','Sakit Ringan','Sakit Sedang','Sakit Berat') CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `kesadaran` enum('Compos Mentis','Apatis','Somnolen','Sopor','Koma') CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `nadi` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `bb` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `td` varchar(8) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `suhu` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `napas` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `tb` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `hepatomegali` enum('Tidak','Ya') CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `splenomegali` enum('Tidak','Ya') CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `ascites` enum('Tidak','Ya') CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `edema` enum('Tidak','Ya') CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `whezzing` enum('Tidak','Ya') CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `ronchi` enum('Tidak','Ya') CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `ikterik` enum('Tidak','Ya') CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `tekanan_vena` enum('Normal','Meningkat') CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `anemia` enum('Tidak','Ya') CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `kardiomegali` enum('Tidak','Ya') CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `bising` enum('Tidak','Ya') CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `thorax` enum('Tidak','Ya') CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `tanggal_thorax` date NOT NULL,
  `ekg` enum('Tidak','Ya') CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `tanggal_ekg` date NOT NULL,
  `bno` enum('Tidak','Ya') CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `tanggal_bno` date NOT NULL,
  `usg` enum('Tidak','Ya') CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `tanggal_usg` date NOT NULL,
  `renogram` enum('Tidak','Ya') CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `tanggal_renogram` date NOT NULL,
  `biopsi` enum('Tidak','Ya') CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `tanggal_biopsi` date NOT NULL,
  `ctscan` enum('Tidak','Ya') CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `tanggal_ctscan` date NOT NULL,
  `arteriografi` enum('Tidak','Ya') CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `tanggal_arteriografi` date NOT NULL,
  `kultur_urin` enum('Tidak','Ya') CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `tanggal_kultur_urin` date NOT NULL,
  `laborat` enum('Tidak','Ya') CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `tanggal_laborat` date NOT NULL,
  `hematokrit` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `hemoglobin` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `leukosit` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `trombosit` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `hitung_jenis` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `ureum` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `urin_lengkap` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `kreatinin` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `cct` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `sgot` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `sgpt` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `ct` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `asam_urat` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `hbsag` enum('Non Reaktif','Reaktif') CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `anti_hcv` enum('Non Reaktif','Reaktif') CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `edukasi` varchar(1000) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  PRIMARY KEY (`no_rawat`) USING BTREE,
  INDEX `kd_dokter`(`kd_dokter`) USING BTREE,
  CONSTRAINT `penilaian_medis_hemodialisa_ibfk_1` FOREIGN KEY (`no_rawat`) REFERENCES `sik`.`reg_periksa` (`no_rawat`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `penilaian_medis_hemodialisa_ibfk_2` FOREIGN KEY (`kd_dokter`) REFERENCES `sik`.`dokter` (`kd_dokter`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

ALTER TABLE `sik`.`set_akun` DROP FOREIGN KEY `set_akun_ibfk_58`;

ALTER TABLE `sik`.`set_akun` DROP FOREIGN KEY `set_akun_ibfk_59`;

ALTER TABLE `sik`.`set_akun` DROP FOREIGN KEY `set_akun_ibfk_60`;

ALTER TABLE `sik`.`set_akun` DROP FOREIGN KEY `set_akun_ibfk_61`;

ALTER TABLE `sik`.`set_akun` DROP FOREIGN KEY `set_akun_ibfk_62`;

ALTER TABLE `sik`.`set_akun` DROP FOREIGN KEY `set_akun_ibfk_63`;

ALTER TABLE `sik`.`set_akun` ADD CONSTRAINT `set_akun_ibfk_58` FOREIGN KEY (`Pengadaan_Dapur`) REFERENCES `sik`.`rekening` (`kd_rek`) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE `sik`.`set_akun` ADD CONSTRAINT `set_akun_ibfk_59` FOREIGN KEY (`Stok_Keluar_Dapur`) REFERENCES `sik`.`rekening` (`kd_rek`) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE `sik`.`set_akun` ADD CONSTRAINT `set_akun_ibfk_60` FOREIGN KEY (`Kontra_Stok_Keluar_Dapur`) REFERENCES `sik`.`rekening` (`kd_rek`) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE `sik`.`set_akun` ADD CONSTRAINT `set_akun_ibfk_61` FOREIGN KEY (`PPN_Keluaran`) REFERENCES `sik`.`rekening` (`kd_rek`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `sik`.`set_akun` ADD CONSTRAINT `set_akun_ibfk_62` FOREIGN KEY (`Diskon_Piutang`) REFERENCES `sik`.`rekening` (`kd_rek`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `sik`.`set_akun` ADD CONSTRAINT `set_akun_ibfk_63` FOREIGN KEY (`Piutang_Tidak_Terbayar`) REFERENCES `sik`.`rekening` (`kd_rek`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `sik`.`set_akun_mandiri` ADD COLUMN `kode_rs` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL AFTER `client_secret`;

CREATE TABLE `sik`.`tagihan_mandiri`  (
  `no_rkm_medis` varchar(15) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `nm_pasien` varchar(40) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `alamat` varchar(200) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `jk` enum('L','P') CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `tgl_lahir` date NOT NULL,
  `umurdaftar` varchar(7) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `tgl_registrasi` date NULL DEFAULT NULL,
  `no_nota` varchar(17) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `besar_bayar` double NULL DEFAULT NULL,
  `no_rawat` varchar(17) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `status_lanjut` enum('Ranap','Ralan','Jual Bebas','Deposit','Bayar Piutang') CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `tgl_closing` date NULL DEFAULT NULL,
  `status_bayar` enum('Sudah','Pending') CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `pembatalan` enum('Belum Dibatalkan','Sudah Dibatalkan') CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `dibatalkan_oleh` enum('MHAS','Faskes') CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `besar_batal` double NULL DEFAULT NULL,
  `kasir` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `tambahan1` varchar(75) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `tambahan2` varchar(75) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `tambahan3` varchar(75) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `diupdatebank` datetime NULL DEFAULT NULL,
  `referensi` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `statuscode` enum('Sukses Flagging','Gagal Flagging') CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `keterangan` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  PRIMARY KEY (`no_nota`) USING BTREE,
  INDEX `no_rkm_medis`(`no_rkm_medis`) USING BTREE,
  CONSTRAINT `tagihan_mandiri_ibfk_1` FOREIGN KEY (`no_rkm_medis`) REFERENCES `sik`.`pasien` (`no_rkm_medis`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE = InnoDB CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

ALTER TABLE `sik`.`user` ADD COLUMN `penilaian_medis_hemodialisa` enum('true','false') CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `akun_host_to_host_bank_mandiri`;

ALTER TABLE `sik`.`user` ADD COLUMN `penilaian_lanjutan_resiko_jatuh_psikiatri` enum('true','false') CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `penilaian_level_kecemasan_ranap_anak`;

ALTER TABLE `sik`.`user` DROP COLUMN `penilaian_medis_ralan_hemodialisa`;

SET FOREIGN_KEY_CHECKS=1;