/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * DlgAdmin.java
 *
 * Created on 04 Des 13, 12:59:34
 */
package khanzahmsanjungan;

import fungsi.sekuel;
import java.awt.Cursor;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Kode
 */
public class DlgCekSKDPKontrol extends javax.swing.JDialog {
    
    private sekuel Sequel = new sekuel();

    /**
     * Creates new form DlgAdmin
     *
     * @param parent
     * @param id
     */
    public DlgCekSKDPKontrol(java.awt.Frame parent, boolean id) {
        super(parent, id);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        PanelWall = new usu.widget.glass.PanelGlass();
        jPanel1 = new component.Panel();
        textNoSKDP = new component.TextBox();
        jLabel28 = new component.Label();
        buttonTutup = new widget.ButtonBig();
        buttonCekNoSKDP = new widget.ButtonBig();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new java.awt.BorderLayout(1, 1));

        jPanel2.setBackground(new java.awt.Color(238, 238, 255));
        jPanel2.setForeground(new java.awt.Color(238, 238, 255));

        PanelWall.setBackground(new java.awt.Color(238, 238, 255));
        PanelWall.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/bpjs-amiz.png"))); // NOI18N
        PanelWall.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_STRECT);
        PanelWall.setForeground(new java.awt.Color(238, 238, 255));
        PanelWall.setPreferredSize(new java.awt.Dimension(500, 150));
        PanelWall.setRound(false);
        PanelWall.setWarna(new java.awt.Color(238, 238, 255));

        javax.swing.GroupLayout PanelWallLayout = new javax.swing.GroupLayout(PanelWall);
        PanelWall.setLayout(PanelWallLayout);
        PanelWallLayout.setHorizontalGroup(
            PanelWallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        PanelWallLayout.setVerticalGroup(
            PanelWallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        jPanel2.add(PanelWall);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(238, 238, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 215, 255)), "::[ Cek Data Kontrol BPJS!!! ]::", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Poppins", 0, 24), new java.awt.Color(0, 131, 62))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(0, 131, 62));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 70));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        textNoSKDP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 131, 62), 2, true));
        textNoSKDP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textNoSKDP.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
        textNoSKDP.setPreferredSize(new java.awt.Dimension(350, 75));
        textNoSKDP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textNoSKDPKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(textNoSKDP, gridBagConstraints);

        jLabel28.setForeground(new java.awt.Color(0, 131, 62));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("No. Surat Kontrol");
        jLabel28.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
        jLabel28.setPreferredSize(new java.awt.Dimension(300, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.ipady = 5;
        jPanel1.add(jLabel28, gridBagConstraints);

        buttonTutup.setBackground(new java.awt.Color(255, 255, 255));
        buttonTutup.setForeground(new java.awt.Color(51, 51, 51));
        buttonTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/exit.png"))); // NOI18N
        buttonTutup.setMnemonic('U');
        buttonTutup.setToolTipText("Alt+U");
        buttonTutup.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonTutup.setHorizontalTextPosition(javax.swing.SwingConstants.TRAILING);
        buttonTutup.setIconTextGap(2);
        buttonTutup.setMargin(new java.awt.Insets(0, 0, 0, 0));
        buttonTutup.setPreferredSize(new java.awt.Dimension(100, 75));
        buttonTutup.setVerticalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTutupActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 14;
        jPanel1.add(buttonTutup, gridBagConstraints);

        buttonCekNoSKDP.setBackground(new java.awt.Color(255, 255, 255));
        buttonCekNoSKDP.setForeground(new java.awt.Color(51, 51, 51));
        buttonCekNoSKDP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/konfirmasi.png"))); // NOI18N
        buttonCekNoSKDP.setMnemonic('U');
        buttonCekNoSKDP.setToolTipText("Alt+U");
        buttonCekNoSKDP.setFont(new java.awt.Font("Poppins", 1, 11)); // NOI18N
        buttonCekNoSKDP.setIconTextGap(0);
        buttonCekNoSKDP.setMargin(new java.awt.Insets(0, 0, 0, 0));
        buttonCekNoSKDP.setPreferredSize(new java.awt.Dimension(100, 75));
        buttonCekNoSKDP.setVerticalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonCekNoSKDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCekNoSKDPActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 14;
        jPanel1.add(buttonCekNoSKDP, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNoSKDPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textNoSKDPKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (Sequel.cariInteger("select count(bridging_surat_kontrol_bpjs.no_surat) from bridging_surat_kontrol_bpjs where bridging_surat_kontrol_bpjs.no_surat = ?", textNoSKDP.getText()) > 0) {
                this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                DlgRegistrasiSEPPertama form = new DlgRegistrasiSEPPertama(null, true);
                form.tampilKontrol(textNoSKDP.getText());
                form.setSize(this.getWidth(), this.getHeight());
                form.setLocationRelativeTo(jPanel1);
                this.dispose();
                form.setVisible(true);
                this.setCursor(Cursor.getDefaultCursor());
            } else {
                JOptionPane.showMessageDialog(rootPane, "Data surat kontrol tidak ditemukan!");
            }
        }

    }//GEN-LAST:event_textNoSKDPKeyPressed

    private void buttonCekNoSKDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCekNoSKDPActionPerformed
        if (Sequel.cariInteger("select count(bridging_surat_kontrol_bpjs.no_surat) from bridging_surat_kontrol_bpjs where bridging_surat_kontrol_bpjs.no_surat = ?", textNoSKDP.getText()) > 0) {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            DlgRegistrasiSEPPertama form = new DlgRegistrasiSEPPertama(null, true);
            form.tampilKontrol(textNoSKDP.getText());
            form.setSize(this.getWidth(), this.getHeight());
            form.setLocationRelativeTo(jPanel1);
            this.dispose();
            form.setVisible(true);
            this.setCursor(Cursor.getDefaultCursor());
        } else {
            JOptionPane.showMessageDialog(rootPane, "Data surat kontrol tidak ditemukan!");
        }
    }//GEN-LAST:event_buttonCekNoSKDPActionPerformed

    private void buttonTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTutupActionPerformed
        dispose();
    }//GEN-LAST:event_buttonTutupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgCekSKDPKontrol dialog = new DlgCekSKDPKontrol(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private usu.widget.glass.PanelGlass PanelWall;
    private widget.ButtonBig buttonCekNoSKDP;
    private widget.ButtonBig buttonTutup;
    private component.Label jLabel28;
    private component.Panel jPanel1;
    private javax.swing.JPanel jPanel2;
    private component.TextBox textNoSKDP;
    // End of variables declaration//GEN-END:variables
}
